# ==========================================
# CONFIGURAÇÃO GERAL DA APLICAÇÃO
# ==========================================
spring.application.name=Blockchain
server.port=8080

# ==========================================
# CONFIGURAÇÃO DA BLOCKCHAIN (Hyperledger Besu / EVM)
# ==========================================
# URL do Nó JSON-RPC (Besu local ou remoto)
blockchain.rpc.url=${BLOCKCHAIN_RPC_URL:http://localhost:8545}

# Identificador da Rede Privada (Chain ID)
blockchain.chain-id=${BLOCKCHAIN_CHAIN_ID:1337}

# Endereço do Smart Contract implantado
blockchain.contract.address=${BLOCKCHAIN_CONTRACT_ADDRESS:0x0000000000000000000000000000000000000000}

# Keystore / Carteira do Banco Emissor
blockchain.wallet.file=${BLOCKCHAIN_WALLET_FILE:src/main/resources/keystore/wallet.json}
blockchain.wallet.password=${BLOCKCHAIN_WALLET_PASSWORD:senha_segura_aqui}

# Configurações de Gas (GasPrice = 0 para Rede Privada Consorciada)
blockchain.gas.price=0
blockchain.gas.limit=3000000

spring.profiles.active=dev